ASP.NET_Homework4/Entities/Product.cs
using System.ComponentModel.DataAnnotations;

namespace ASP.NET_Homework4.Entities
{
    public class Product
    {
        public int Id { get; set; }
        [Required(ErrorMessage = ("Name is Required"))]

        [MinLength(3, ErrorMessage = "Minimum name should be 3")]
        public string Name { get; set; }

        [Required(ErrorMessage = ("Description Is Required"))]

        [MinLength(5, ErrorMessage = "Minimum description should be 5")]
        public string Description { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Value must be at least 1.")]
        public int Discount { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Value must be at least 1.")]
        public int Price { get; set; }
        public Product()
        {

        }
        public Product(int ıd, string name, string description, int discount, int price)
        {
            Id = ıd;
            Name = name;
            Description = description;
            Discount = discount;
            Price = price;
        }

    }
}

ASP.NET_Homework4/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ASP.NET_Homework4.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

ASP.NET_Homework4/Pages/Index.cshtml.cs
using ASP.NET_Homework4.Entities;
using ASP.NET_Homework4.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.VisualBasic;

namespace ASP.NET_Homework4.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IProductService _productService;

        public IndexModel(IProductService productService)
        {
            _productService = productService;
        }

        public List<Product> Products { get; set; }
        public void OnGet()
        {
            Products = _productService.GetAllAsync();
        }

        [BindProperty]
        public Product Product { get; set; }

        public IActionResult OnPostAddProductAsync()
        {
            _productService.AddAsync(Product);
            Products = _productService.GetAllAsync();
            return RedirectToPage();
        }

        [BindProperty]
        public Product EditProduct { get; set; }

        public IActionResult OnPostEditProductAsync(int id)
        {
            EditProduct = _productService.GetByIdAsync(id);
            Products = _productService.GetAllAsync();
            return Page();
        }

        public IActionResult OnPostUpdateProductAsync()
        {
            
            _productService.UpdateAsync(EditProduct);
            Products = _productService.GetAllAsync();

            return RedirectToPage();
        }

        

        public IActionResult OnPostDelete()
        {
            var id = Request.Form["id"];
            if (int.TryParse(id, out int productId))
            {
                _productService.DeleteAsync(productId);
                
            }

            return RedirectToPage("Index");
        }

    }
}

ASP.NET_Homework4/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASP.NET_Homework4.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

ASP.NET_Homework4/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Price</th>
            <th scope="col">Discount</th>
            <th scope="col">#</th>
            <th scope="col">#</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.Products)
        {
            <tr>
                <td scope="row">@item.Id</td>
                <td scope="row">@item.Name</td>
                <td scope="row">@item.Description</td>
                <td scope="row">@item.Price</td>
                <td scope="row">@item.Discount</td>
                <td scope="row">
                    <form method="post" asp-page-handler="EditProduct">
                        <input type="hidden" name="id" value="@item.Id" />
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </form>
                </td>
                <td scope="row">
                    <form method="post" asp-page-handler="Delete">
                        <input type="hidden" name="id" value="@item.Id" />
                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                        @* <button type="submit" class="btn btn-danger btn-sm">Delete</button> *@
                    </form>
                </td>
            </tr>
        }


    </tbody>
</table>

@if (Model.EditProduct == null)
{
    <form class="col-5" method="post" asp-page-handler="AddProduct">
        <div class="mb-3">
            <label class="form-label">Product Name</label>
            <input required asp-for="Product.Name" class="form-control" />
            <span asp-validation-for="Product.Name" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label class="form-label">Product Description</label>
            <input required asp-for="Product.Description" class="form-control" />
            <span asp-validation-for="Product.Description" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label class="form-label">Product Price</label>
            <input required asp-for="Product.Price" class="form-control" />
            <span asp-validation-for="Product.Price" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label class="form-label">Product Discount</label>
            <input required asp-for="Product.Discount" class="form-control" />
            <span asp-validation-for="Product.Discount" class="text-danger"></span>

        </div>
        <button type="submit" class="btn btn-success">Add Product</button>
    </form>
}

@if(Model.EditProduct != null)
{
    <form class="col-5" method="post" asp-page-handler="UpdateProduct">
        <input type="hidden" asp-for="EditProduct.Id" />
        <div class="mb-3">
            <label class="form-label">Product Name</label>
            <input required asp-for="EditProduct.Name" class="form-control" />
            <span asp-validation-for="EditProduct.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label">Product Description</label>
            <input required asp-for="EditProduct.Description" class="form-control" />
            <span asp-validation-for="EditProduct.Description" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label class="form-label">Product Price</label>
            <input required asp-for="EditProduct.Price" class="form-control" />
            <span asp-validation-for="EditProduct.Price" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label class="form-label">Product Discount</label>
            <input required asp-for="EditProduct.Discount" class="form-control" />
            <span asp-validation-for="EditProduct.Discount" class="text-danger"></span>

        </div>
        <button type="submit" class="btn btn-success">Update Product</button>
    </form>
}  

ASP.NET_Homework4/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NET_Homework4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NET_Homework4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ASP.NET_Homework4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ASP.NET_Homework4 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>